const POSTHOG_HOST = "https://us.posthog.com"; // match your project's region
const PROJECT_ID = process.env.POSTHOG_PROJECT_ID!;
const API_KEY = process.env.POSTHOG_PERSONAL_API_KEY!;

async function posthogRequest(path: string, options: RequestInit = {}) {
  const response = await fetch(`${POSTHOG_HOST}/api/projects/${PROJECT_ID}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${API_KEY}`,
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
  if (!response.ok) {
    throw new Error(`PostHog API error ${response.status}: ${await response.text()}`);
  }
  return response.json();
}

async function findExistingInsight(name: string) {
  const results = await posthogRequest(`/insights/?search=${encodeURIComponent(name)}`);
  return results.results?.find((i: { name: string }) => i.name === name);
}

async function upsertInsight(definition: InsightDefinition) {
  const existing = await findExistingInsight(definition.name);
  if (existing) {
    console.log(`Skipping "${definition.name}" — already exists (id ${existing.id}). Delete it in the UI first to recreate.`);
    return existing;
  }
  const created = await posthogRequest("/insights/", {
    method: "POST",
    body: JSON.stringify(definition.payload),
  });
  console.log(`Created "${definition.name}" (id ${created.id})`);
  return created;
}

async function createDashboard(name: string) {
  return posthogRequest("/dashboards/", {
    method: "POST",
    body: JSON.stringify({ name, description: "Auto-generated by posthog-setup.ts — see script for source of truth." }),
  });
}

async function addInsightToDashboard(dashboardId: number, insightId: number) {
  await posthogRequest(`/insights/${insightId}/`, {
    method: "PATCH",
    body: JSON.stringify({ dashboards: [dashboardId] }),
  });
}

type InsightDefinition = { name: string; payload: Record<string, unknown> };

const funnels: InsightDefinition[] = [
  {
    name: "Activation: install → first optimization",
    payload: {
      name: "Activation: install → first optimization",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "FunnelsQuery",
          series: [
            { kind: "EventsNode", event: "extension_installed", name: "extension_installed" },
            { kind: "EventsNode", event: "extension_authenticated", name: "extension_authenticated" },
            { 
              kind: "EventsNode", 
              event: "optimization_run", 
              name: "optimization_run", 
              properties: [{ key: "is_first_optimization", value: "true", operator: "exact", type: "event" }] 
            },
          ],
          funnelsFilter: {
            funnelVizType: "steps",
            funnelWindowInterval: 7,
            funnelWindowIntervalUnit: "day",
          }
        }
      },
    },
  },
  {
    name: "Upgrade intent: locked mode → checkout completed",
    payload: {
      name: "Upgrade intent: locked mode → checkout completed",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "FunnelsQuery",
          series: [
            { kind: "EventsNode", event: "locked_mode_clicked", name: "locked_mode_clicked" },
            { kind: "EventsNode", event: "upgrade_link_clicked", name: "upgrade_link_clicked" },
            { kind: "EventsNode", event: "checkout_started", name: "checkout_started" },
            { kind: "EventsNode", event: "checkout_completed", name: "checkout_completed" },
          ],
          funnelsFilter: {
            funnelVizType: "steps",
            funnelWindowInterval: 3,
            funnelWindowIntervalUnit: "day",
          },
          breakdownFilter: {
            breakdown: "current_tier",
            breakdown_type: "event",
          }
        }
      },
    },
  },
  {
    name: "Credit pressure: exhausted → upgrade click (same session)",
    payload: {
      name: "Credit pressure: exhausted → upgrade click (same session)",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "FunnelsQuery",
          series: [
            { kind: "EventsNode", event: "credits_exhausted", name: "credits_exhausted" },
            { kind: "EventsNode", event: "upgrade_link_clicked", name: "upgrade_link_clicked" },
          ],
          funnelsFilter: {
            funnelVizType: "steps",
            funnelWindowInterval: 1,
            funnelWindowIntervalUnit: "day",
          },
          breakdownFilter: {
            breakdown: "current_tier",
            breakdown_type: "event",
          }
        }
      },
    },
  },
  {
    name: "Save-to-library adoption: optimization → snippet saved",
    payload: {
      name: "Save-to-library adoption: optimization → snippet saved",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "FunnelsQuery",
          series: [
            { kind: "EventsNode", event: "optimization_run", name: "optimization_run" },
            { kind: "EventsNode", event: "history_drawer_opened", name: "history_drawer_opened" },
            { kind: "EventsNode", event: "snippet_saved", name: "snippet_saved" },
          ],
          funnelsFilter: {
            funnelVizType: "steps",
            funnelWindowInterval: 1,
            funnelWindowIntervalUnit: "day",
          }
        }
      },
    },
  },
];

const trends: InsightDefinition[] = [
  {
    name: "Optimization mode distribution",
    payload: {
      name: "Optimization mode distribution",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "TrendsQuery",
          series: [
            { kind: "EventsNode", event: "optimization_run", name: "optimization_run", math: "total" }
          ],
          trendsFilter: {
            display: "ActionsBarValue",
          },
          breakdownFilter: {
            breakdown: "mode",
            breakdown_type: "event",
          }
        }
      },
    },
  },
  {
    name: "Optimizations by platform (ChatGPT / Claude / Gemini)",
    payload: {
      name: "Optimizations by platform (ChatGPT / Claude / Gemini)",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "TrendsQuery",
          series: [
            { kind: "EventsNode", event: "optimization_run", name: "optimization_run", math: "total" }
          ],
          trendsFilter: {
            display: "ActionsLineGraph",
          },
          breakdownFilter: {
            breakdown: "platform",
            breakdown_type: "event",
          }
        }
      },
    },
  },
  {
    name: "Optimization failure rate",
    payload: {
      name: "Optimization failure rate",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "TrendsQuery",
          series: [
            { kind: "EventsNode", event: "optimization_run", name: "optimization_run", math: "total" },
            { kind: "EventsNode", event: "optimization_failed", name: "optimization_failed", math: "total" }
          ],
          trendsFilter: {
            display: "ActionsLineGraph",
            formula: "B / (A + B)",
          }
        }
      },
    },
  },
  {
    name: "Input detection failures by platform",
    payload: {
      name: "Input detection failures by platform",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "TrendsQuery",
          series: [
            { kind: "EventsNode", event: "input_detection_failed", name: "input_detection_failed", math: "total" }
          ],
          trendsFilter: {
            display: "ActionsLineGraph",
          },
          breakdownFilter: {
            breakdown: "platform",
            breakdown_type: "event",
          }
        }
      },
    },
  },
];

const retention: InsightDefinition[] = [
  {
    name: "Weekly retention by plan tier",
    payload: {
      name: "Weekly retention by plan tier",
      query: {
        kind: "InsightVizNode",
        source: {
          kind: "RetentionQuery",
          retentionFilter: {
            period: "Week",
            targetEntity: { id: "optimization_run", type: "events", name: "optimization_run" },
            returningEntity: { id: "optimization_run", type: "events", name: "optimization_run" }
          },
          breakdownFilter: {
            breakdown: "plan_tier",
            breakdown_type: "person",
          }
        }
      },
    },
  },
];

async function main() {
  const dashboard = await createDashboard("PromptPro — Core Metrics");

  for (const def of [...funnels, ...trends, ...retention]) {
    const insight = await upsertInsight(def);
    await addInsightToDashboard(dashboard.id, insight.id);
  }

  console.log(`Done. Dashboard: ${POSTHOG_HOST}/project/${PROJECT_ID}/dashboard/${dashboard.id}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
